let database = [
  {
    id: 1,
    title: "Kingsman: The Secret Service",
    year: 2014,
    director: "Matthew Vaughn",
    actors: [
      "Taron Egerton",
      "Colin Firth",
      "Mark Strong",
      "Samuel L. Jackson",
    ],
    genre: ["Action", "Comedy"],
    runtime: 129,
    oscarAward: false,
    studio: "20th Century Fox",
  },

  {
    id: 2,
    title: "Ghostbusters",
    year: 1984,
    director: "Ivan Reitman",
    actors: [
      "Dan Aykroyd",
      "Bill Murray",
      "Harold Ramis",
      "Ernie Hudson",
      "Sigourney Weaver",
    ],
    genre: ["Comedy, Fantasy"],
    runtime: 107,
    oscarAward: false,
    studio: "Columbia Pictures",
  },

  {
    id: 3,
    title: "Rocketman",
    year: 2019,
    director: "Dexter Fletcher",
    actors: ["Taron Egerton", "Jamie Bell", "Richard Madden"],
    genre: ["Drama", "Music"],
    runtime: 121,
    oscarAward: false,
    studio: "Paramount",
  },

  {
    id: 4,
    title: "La La Land",
    year: 2016,
    director: "Damien Chazelle",
    actors: ["Emma Stone", "Ryan Gosling"],
    genre: ["Music", "Drama", "Romance"],
    runtime: 129,
    oscarAward: false,
    studio: "Summit Entertainment",
  },

  {
    id: 5,
    title: "Lilo & Stitch",
    year: 2002,
    director: ["Dean DeBlois", "Chris Sanders"],
    actors: [
      "Daveigh Chase",
      "Chris Sanders",
      "Tia Carrere",
      "David Ogden Stiers",
      "Kevin McDonald",
    ],
    genre: ["Animation", "Family"],
    runtime: 85,
    oscarAward: true,
    studio: "Disney",
  },

  {
    id: 6,
    title: "Harry Potter & The Prisoner of Azkaban",
    year: 2004,
    director: "Alfonso Cuarón",
    actors: [
      "Daniel Radcliffe",
      "Rupert Grint",
      "Emma Watson",
      "David Thewlis",
      "Gary Oldman",
    ],
    genre: ["Fantasy", "Adventure"],
    runtime: 141,
    oscarAward: false,
    studio: "Warner Bros. Pictures",
  },

  {
    id: 7,
    title: "Parasite",
    year: 2020,
    director: "Bong Joon-ho ",
    actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    genre: ["Drama", "Thriller"],
    runtime: 133,
    oscarAward: true,
    studio: "Barunson E&A",
  },

  {
    id: 8,
    title: "Logan",
    year: 2017,
    director: "James Mangold",
    actors: ["Hugh Jackman", "Dafne Keen", "Patrick Stewart"],
    genre: ["Action", "Science Fiction"],
    runtime: 137,
    oscarAward: false,
    studio: "20th Century Fox",
  },

  {
    id: 9,
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    actors: ["Tim Robbins", "Morgan Freeman"],
    genre: ["Drama", "Crime"],
    runtime: 142,
    oscarAward: true,
    studio: "Castle Rock Entertainment",
  },

  {
    id: 10,
    title: "Knives Out",
    year: 2019,
    director: "Rian Johnson",
    actors: ["Ana de Armas", "Daniel Craig", "Chris Evans", "Jamie Lee Curtis"],
    genre: ["Mystery", "Comedy"],
    runtime: 131,
    oscarAward: false,
    studio: "Lionsgate",
  },
];
